# Generated by Django 4.2.2 on 2023-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
